CREATE TABLE IF NOT EXISTS products_commands (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  quantity INTEGER NOT NULL,
  productId INTEGER NOT NULL FOREIGN KEY REFERENCES products(productId),
  commandId INTEGER NOT NULL FOREIGN KEY REFERENCES commands(commandId)
);
